### ISSUE TITLE
elixir?

### ISSUE THREAD

**Issue by kosir** [wozniakjan/erlcart#2]
Hi, thanks for this cartridge setup! I just started with functional programming and I'm using elixir/phoenix for backend and elm for frontend. Do you maybe have any knowledge/experience if it is possible to run such combination on openshift paas? Thanks in advance for any reply!

**Comment by wozniakjan** [comment]
Hi, unfortunately I don't have any experience with elixir yet, but I will take a look this weekend.

Thanks for the feedback!

**Comment by wozniakjan** [comment]
I have added elixir to the cartridge. You can now use it through the git repository as well as call and experiment from cmd line if you ssh to your openshift app using this cartridge. But when you ssh, don't forget to add your `/usr/bin` to your `PATH` and also keep in mind that shell access is quite powerfull and openshift is ment to be used through its git interface.

```
export PATH=$OPENSHIFT_ERL_DIR/usr/bin/:$PATH
```
