### ISSUE TITLE
Phoenix framework?

### ISSUE THREAD

**Issue by kosir** [wozniakjan/erlcart#4]
Hi, thanks for your code. I'm learning Elixir/Phoenix, I installed it on c9 workspace (erlang, elixir, phoenix) and it works really fine, when I see "Sent 200 in 301µs" it's good feeling and with live reload and all.. it's like sitting on a brand new bike :)
Just wondering if you could help to run same configuration on openshift, which I'm using for long time, mostly wordpress sites for small clients. I can give you link to my c9 workspace and super easy script to install all what is needed (also cloud9 is a bit tricky), which I found here: https://medium.com/@Oxyrus/how-to-install-the-phoenix-framework-on-cloud9-ef0ac265229c#.jnuen1csb
Thanks in advance for any reply!

**Comment by wozniakjan** [comment]
Hi, unfortunately I am currently a bit time constrained, but I promise to get back to you once there is some free time for hobbies on my hands. That is unlikely going to be this month, my apologies if your issue is time critical.

**Comment by kosir** [comment]
That's great, thank you so much. It't nothing time critical at all. Looking forward :)

**Comment by wozniakjan** [comment]
I spent some time looking at the issue and it looks like the 'mix' is using erlang's module httpc, and tries to bind to localhost. This is not possible on OpenShift and, therefore, mix always fails. I will check if I can find where to modify erlang/otp/elixir/mix code or bypass mix completely to get the Phoenix going.

**Comment by kosir** [comment]
Thanks, that's great news for me, that you started to work on this... If you want me to test anything, don't hesitate to contact me (I'm still in learning process of elixir). I decided to switch to this stack (erlang/elixir/phoenix) for backend in next months (maybe I would use rethinkdb instead of postgresql) and probably elm for frontend. I've seen that "normal" phoenix deployment is heroku but I have (mostly) great experience with openshift in last years, so I would prefer to have it there (it is also much more convenient for small clients to have free site while they are small), which is not possible on heroku, I think.

**Comment by wozniakjan** [comment]
Hi, I have finally found enough time to get the phoenix up and running. Please note that the repository's master branch serves as disambiguation for two other branches - cowboy and phoenix. The phoenix needed some workarounds and tweaks, but let http://phoenix-wozj.rhcloud.com/ serve as a proof that it can run on openshift after all :)

**Comment by bZichett** [comment]
@wozniakjan You are a shining beacon of light, good sir =)

**Comment by wozniakjan** [comment]
thank you for the kind words, hopefully the workarounds are not too limiting for your case.

**Comment by kosir** [comment]
Oh, man, this made my day ! Thank you soooo much! I will try to run this on my openshift account and let you know how it goes as soon as I find a free hour of time (we are in the middle of summer season here and we a running a hostel here in Pula/Croatia, so fully busy right now..)
Thanks again!
